### ISSUE TITLE
ValueError: GRU(reset_after=False) is not compatible with GRU(reset_after=True)

### ISSUE THREAD

**Issue by sri1905** [notAI-tech/DeepTranslit#2]
On running **transliterator = DeepTranslit('telugu')** in google colab, I get a value error. This happens irrespective of the language. Please find attached the error log. Do suggest on how to resolve this. Thank you.
![Screenshot from 2020-11-25 20-36-38](https://user-images.githubusercontent.com/14858682/100245639-49694880-2f5e-11eb-960a-484e763a55e3.png)

**Comment by bedapudi6788** [comment]
I haven't tested txt2txt (https://github.com/bedapudi6788/txt2txt) with recent versions of tf yet. tf 1.15, keras 2.2.4 should work (If I recall correctly, tensorflow versions upto 2.1 works.). `%tensorflow_version 1.x` this enables tensorflow 1.15 on colab.

**Comment by sri1905** [comment]
Despite this `%tensorflow_version 1.x` , I am running into the same error (ValueError)

**Comment by bedapudi6788** [comment]
Can you share the colab notebook?

**Comment by sri1905** [comment]
https://colab.research.google.com/drive/1MpCHB2d2DSrqUgLxPMCjTb6Kp3aNY92a?usp=sharing

That should give access to edit. Thank you

**Comment by bedapudi6788** [comment]
https://colab.research.google.com/drive/1ifLfqaeAA2tHSHDaS_BiCIDXy3-_k0tp?usp=sharing

**Comment by bedapudi6788** [comment]
@sri1905 above colab demonstrates the usage. Closing the issue. Feel free to re-open if required.

**Comment by sri1905** [comment]
Now I get the following error:
AttributeError: module 'tensorflow' has no attribute 'get_default_graph'

Tried to add some import statements and change the way tf calls this in the dist-packages's file but its not changing anything.
