### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'get_default_graph'

### ISSUE THREAD

**Issue by sri1905** [notAI-tech/DeepTranslit#3]
Now I get this error. I could not re-open the last issue. Following some stackoverflow answers, I have tried importing in the following manner and changing the way tf call 'get_default_graph'  but it's not helping. 

https://colab.research.google.com/drive/1MpCHB2d2DSrqUgLxPMCjTb6Kp3aNY92a?usp=sharing

Thank you.

**Comment by bedapudi6788** [comment]
did the colab notebook I shared not work? in the above colab notebook, it clearly shows that the version of tensorflow being used if tf 2.3.1 and it prints the message `TensorFlow is already loaded. Please restart the runtime to change versions.`

Reading the printed logs is a good idea.

**Comment by sri1905** [comment]
I have restarted it twice, once for tensorflow and again for keras. After restarting, it gives this new AttributeError.

**Comment by bedapudi6788** [comment]
Can you just follow the exact same steps demonstrated in https://colab.research.google.com/drive/1ifLfqaeAA2tHSHDaS_BiCIDXy3-_k0tp?usp=sharing . Since I made this notebook only a few hours back, it should work.

**Comment by sri1905** [comment]
![Screenshot from 2020-11-25 23-00-21](https://user-images.githubusercontent.com/14858682/100262980-ed5cef00-2f72-11eb-9182-ff93ad88466f.png)
It's very strange, it worked the first time but when I ran all commands again, I get a prompt to `Restart Runtime`. After I clicked that, I got the same AttributeError even in the Copy of testing.ipynb.

Also, I have copied line to line in testing.ipynb from the notebook you have shared and everytime it gave the same AttributeError. https://colab.research.google.com/drive/1MpCHB2d2DSrqUgLxPMCjTb6Kp3aNY92a?usp=sharing

Since the above link gives edit access, is it possible for you to test and make changes to that notebook itself ? Thank you very much.

**Comment by bedapudi6788** [comment]
@sri1905 I am sorry, but I cannot spend my time figuring how to setup some environment. In general, if you get tf 1.15 and keras 2.2.4 working in an environment, deeptranslit will work.

**Comment by sri1905** [comment]
okay, Thank you

**Comment by bedapudi6788** [comment]
https://colab.research.google.com/notebooks/tensorflow_version.ipynb this might be helpful.
