### ISSUE TITLE
Not working with latest version of Tensorflow and Keras

### ISSUE THREAD

**Issue by raghuk-botaiml** [notAI-tech/DeepTranslit#4]
I tried installing the module using the command `pip install --upgrade deeptranslit`

After that, I am getting the following error:

> ValueError: GRU(reset_after=False) is not compatible with GRU(reset_after=True)

**Comment by bedapudi6788** [comment]
@raghuk-botaiml at the moment, you will have to fall back to older versions of tf and keras (). I will remove the tf dependency in a future release when I get some time.

**Comment by raghuk-botaiml** [comment]
@bedapudi6788, which version of tf? Because i went back upto v1.8 and it still didn't work.

**Comment by bedapudi6788** [comment]
tf 1.14, keras 2.2.4 are the versions I trained and generally test with. I am sure it works with tf 1.15 and some more newer versions too.
